### ISSUE TITLE
Update the System.Net.Http package since it has security vulnerabilities

### ISSUE THREAD

**Issue by nobba** [nblumhardt/serilog-blazor#23]
We get warnings from our package analyzer and an upgrade from 4.3.0 to 4.3.4 would solve this. I know this is in dev, but it should be a small effort.

**Comment by nblumhardt** [comment]
A PR with dependency updates would be welcome 👍

**Comment by nobba** [comment]
Ok, so looked at the code and this package (and some others) can't be updated in themselfs to a supported version. To get things up to date an update of the target framework is needed (along with other changes required for that). I can look into updating the package to .net 7, but I want to know if it is ok to do that before I dig in?

**Comment by nblumhardt** [comment]
Since netstandard2.1 is still supported this seems like it should be avoidable; it's likely your scanner is reporting based on the minimum package version rather than what's actually running in your app (assuming you're targeting .NET 7 in the app). What assembly version do you find in the app's published output?

**Comment by nobba** [comment]
Ok, dug a bit deeper and it seems that its the xunit packages that pulls in this issue, see here https://github.com/xunit/xunit/issues/2294. Seems to be sorted in v3 whenever that may be published. So as you mention, this should not be a problem in runtime in a .net 7 application. Also not published since part of test projects only.  -> Closing.
